version: "3"
services:
  super-traders:
    image: "node:12"
    container_name: "super-traders"
    volumes:
      - ./dist:/opt/super-traders
    environment:
      POSTGRESQL_HOST: "postgresqlDb"
    working_dir: /opt/super-traders
    command: node app.js -d
    ports:
      - 8082:8082
    depends_on:
      - postgresqlDb
  postgresqlDb:
    image: "postgres:10.14"
    container_name: postgresqlDb
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - 127.0.0.1:5432:5432
